CREATE TABLE ITEM (
  ID                  BIGINT NOT NULL AUTO_INCREMENT,
  MODIFICATIONCOUNTER INTEGER NOT NULL,
  CREATION_DATE       TIMESTAMP WITH TIME ZONE NOT NULL,
  NAME                VARCHAR(255) NOT NULL,
  PRICE               DECIMAL(5, 2) NOT NULL,
  ORDER_ID            BIGINT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ORDER_ID) REFERENCES RESTAURANT_ORDER(ID)
);
