--------------------------------------------------------
-- Description: create movie table
--------------------------------------------------------

CREATE TABLE MOVIE (
  ID      BIGINT NOT NULL,
  MODIFICATIONCOUNTER INTEGER NOT NULL,
  TITLE   VARCHAR2(255 CHAR) NOT NULL,
  YEAR    INTEGER,
  CONSTRAINT PK_MOVIE PRIMARY KEY(ID),
  CONSTRAINT UC_MOVIE_DUBLETTE UNIQUE (TITLE, YEAR)
);


CREATE TABLE MOVIE_GENRE (
  MOVIE_ID	BIGINT NOT NULL,
  GENRE   	VARCHAR2(50 CHAR)  NOT NULL,
  CONSTRAINT UC_MOVIE_GENRE UNIQUE (MOVIE_ID, GENRE)
);
