--------------------------------------------------------
-- Description: create movie data
--------------------------------------------------------


INSERT INTO MOVIE (MODIFICATIONCOUNTER, ID, TITLE, YEAR)
VALUES (0, 1, 'Toy Story', 1995);
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (1, 'ADVENTURE');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (1, 'ANIMATION');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (1, 'CHILDREN');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (1, 'COMEDY');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (1, 'FANTASY');

INSERT INTO MOVIE (MODIFICATIONCOUNTER, ID, TITLE, YEAR)
VALUES (0, 2, 'Jumanji', 1995);
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (2, 'ADVENTURE');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (2, 'CHILDREN');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (2, 'FANTASY');

INSERT INTO MOVIE (MODIFICATIONCOUNTER, ID, TITLE, YEAR)
VALUES (0, 3, 'Heat', 1995);
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (3, 'ACTION');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (3, 'CRIME');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (3, 'THRILLER');

INSERT INTO MOVIE (MODIFICATIONCOUNTER, ID, TITLE, YEAR)
VALUES (0, 4, 'Sabrina', 1995);
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (4, 'COMEDY');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (4, 'ROMANCE');

INSERT INTO MOVIE (MODIFICATIONCOUNTER, ID, TITLE, YEAR)
VALUES (0, 5, 'GoldenEye', 1995);
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (5, 'ACTION');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (5, 'ADVENTURE');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (5, 'THRILLER');

INSERT INTO MOVIE (MODIFICATIONCOUNTER, ID, TITLE, YEAR)
VALUES (0, 6, 'Powder', 1995);
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (6, 'DRAMA');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (6, 'SCI_FI');

INSERT INTO MOVIE (MODIFICATIONCOUNTER, ID, TITLE, YEAR)
VALUES (0, 7, 'Twelve Monkeys (a.k.a. 12 Monkeys)', 1995);
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (7, 'MYSTERY');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (7, 'SCI_FI');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (7, 'THRILLER');

INSERT INTO MOVIE (MODIFICATIONCOUNTER, ID, TITLE, YEAR)
VALUES (0, 8, 'Mortal Kombat', 1995);
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (8, 'ACTION');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (8, 'ADVENTURE');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (8, 'FANTASY');

INSERT INTO MOVIE (MODIFICATIONCOUNTER, ID, TITLE, YEAR)
VALUES (0, 9, 'Seven (a.k.a. Se7en)', 1995);
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (9, 'MYSTERY');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (9, 'THRILLER');

INSERT INTO MOVIE (MODIFICATIONCOUNTER, ID, TITLE, YEAR)
VALUES (0, 10, 'Usual Suspects, The', 1995);
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (10, 'MYSTERY');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (10, 'CRIME');
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE) VALUES (10, 'THRILLER');
